A/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('account/',include('account.urls',namespace='account')),
    path('post/',include('posts.urls',namespace='posts')),
]

account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
  
    path('login/',views.UserLoginView.as_view(),name='login'),
    path('logout/',views.UserLogoutView.as_view(),name='logout'),
    path('register/',views.UserRegisterView.as_view(),name='register'),
    path('profile/<int:user_id>/',views.UserProfileView.as_view(),name='user_profile'),
    path('reset/',views.UserPasswordResetView.as_view(),name='password_reset'),
    path('reset/done/',views.UserPAsswordResetDonView.as_view(),name='password_reset_done'),
    path('confirm/<uidb64>/<token>/',views.UserPasswordresetConfirmView.as_view(),name='password_reset_confirm'),
    path('confirm/complete',views.UserPasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('follow/<int:user_id>',views.UserFollowView.as_view(),name='user_follow'),

    path('unfollow/<int:user_id>',views.UserUnfollowView.as_view(),name='user_unfollow'),
    path('edit_user/',views.EditUserView.as_view(),name='edit_user'),

   
   
]

home/urls.py
from django.urls import path
from . import views




app_name='home'
urlpatterns = [
  
    path('',views.HomeView.as_view(),name='home')
]

posts/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from . import views

app_name='posts'
urlpatterns = [
        path('posts/',views.PostView.as_view(),name='posts'),
        path('details/<int:post_id>/<slug:post_slug>/',views.PostDetailView.as_view(),name='details'),
        path('delete/<int:post_id>',views.PostDeleteView.as_view(),name='delete'),
        path('update/<int:post_id>',views.PostUpdateView.as_view(),name='update'),
        path('create/',views.PostCreateView.as_view(),name='create'),
        path('reply/<int:post_id>/<int:comment_id>',views.PostAddReplyView.as_view(),name='add_reply'),
        path('like/<int:post_id>/',views.PostLikeView.as_view(),name='post_like'),

]

templates/include/messages.html
{% if messages %}

    {% for msg in messages %}

        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>

    {% endfor %}


{% endif %} 

templates/include/navbar.html
<nav class="   navbar navbar-expand-lg bg-black">
    <div class=" container-fluid">

            <div class="navbar-nav">

                    <a class="btn btn-dark "  href="{% url 'home:home' %}">Home</a>
                    <a class="btn btn-dark" href="{% url 'posts:posts'  %}">Time Line</a>
                          

                    {% if request.user.is_authenticated%}


                          <a class="btn btn-dark" href="{% url 'account:logout' %}">Logout</a>
                          <a class="btn btn-dark" href="{% url 'account:user_profile' request.user.id %}">Profile</a>
                    

                      {% else%}

                      <a class="btn btn-dark" href="{%url 'account:login' %}">Login</a>
                      <a class="btn btn-dark "href="{%url 'account:register' %}">Register</a>

                    {% endif %}
            </div>

      <a class="btn btn-info corner", href="{% url 'account:password_reset' %}">Password reset</a>
    </div>
  </nav>