A/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('account/',include('account.urls',namespace='account')),
    path('post/',include('posts.urls',namespace='posts')),
]

account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
  
    path('login/',views.UserLoginView.as_view(),name='login'),
    path('logout/',views.UserLogoutView.as_view(),name='logout'),
    path('register/',views.UserRegisterView.as_view(),name='register'),
    path('profile/<int:user_id>/',views.UserProfileView.as_view(),name='user_profile'),
    path('reset/',views.UserPasswordResetView.as_view(),name='password_reset'),
    path('reset/done/',views.UserPAsswordResetDonView.as_view(),name='password_reset_done'),
    path('confirm/<uidb64>/<token>/',views.UserPasswordresetConfirmView.as_view(),name='password_reset_confirm'),
    path('confirm/complete',views.UserPasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('follow/<int:user_id>',views.UserFollowView.as_view(),name='user_follow'),

    path('unfollow/<int:user_id>',views.UserUnfollowView.as_view(),name='user_unfollow'),
    path('edit_user/',views.EditUserView.as_view(),name='edit_user'),

   
   
]

posts/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from . import views

app_name='posts'
urlpatterns = [
        path('posts/',views.PostView.as_view(),name='posts'),
        path('details/<int:post_id>/<slug:post_slug>/',views.PostDetailView.as_view(),name='details'),
        path('delete/<int:post_id>',views.PostDeleteView.as_view(),name='delete'),
        path('update/<int:post_id>',views.PostUpdateView.as_view(),name='update'),
        path('create/',views.PostCreateView.as_view(),name='create'),
        path('reply/<int:post_id>/<int:comment_id>',views.PostAddReplyView.as_view(),name='add_reply'),
        path('like/<int:post_id>/',views.PostLikeView.as_view(),name='post_like'),

]

posts/models.py
import re
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='posts')
    body=models.TextField()
    slug=models.SlugField(max_length=15,unique=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    

    def __str__(self) -> str:

        return f'{self.slug}-{self.updated}'


    def get_absolute_url(self):
        return reverse('posts:details',args=(self.id,self.slug))

    def likes_count(self):
        return self.post_vote.count()

    def user_can_like(self,user):
        user_like=user.user_vote.filter(post=self)
        if user_like.exists():
            return True
        return False


class Comment(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_comment')
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='post_comment')
    reply=models.ForeignKey('self',on_delete=models.CASCADE,related_name='reply_comment',blank=True,null=True)
    body=models.TextField(max_length=400)
    is_reply=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)




    def __str__(self)->str:
        return f'{self.user} is commented on {self.body[:30]}'





class Vote(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_vote')
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='post_vote')


    def __str__(self) -> str:
        return f'{self.user}liked {self.post.slug}'





        

posts/forms.py
from dataclasses import fields

from django import forms
from .models import Post,Comment


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('body',)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('body',)
        widgets={


            'body':forms.Textarea(attrs={'class':'form-control'})
        }
    
class CommentReplyForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('body',)
        widgets={


            'body':forms.Textarea(attrs={'class':'form-control'})
        }
    
    
    
class PostSearchForm(forms.Form):
    search =forms.CharField()
        
        
        

posts/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views import View 
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from .models import Post,Comment,Vote
from django.contrib import messages
from .forms import PostUpdateForm,CommentCreateForm,CommentReplyForm,PostSearchForm
from django.utils.text import slugify
from django .contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator



class PostView(View):

    form_class=PostSearchForm
    def get(self,request):
        posts=Post.objects.all()


        if request.GET.get('search'):
            posts=posts.filter(body__contains=request.GET['search'])
        
        return render (request,'posts/my_posts.html',{'posts':posts , 'form':self.form_class})



class PostDetailView(View):
    form_class=CommentCreateForm
    form_class_reply=CommentReplyForm

    def setup(self, request , *args: any, **kwargs: any) :
        self.post_instance = get_object_or_404(Post,id=kwargs['post_id'],slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)

    
    def get(self,request,*args,**kwargs):
        can_like=False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            can_like=True

        
        comments=self.post_instance.post_comment.filter(is_reply=False)
        return render(request,'posts/details.html',{'post':self.post_instance ,'comments':comments,'form':self.form_class,\
            'reply_form':self.form_class_reply ,'can_like':can_like})

    @method_decorator(login_required)
    def post(self,request,*args,**kwargs):
        form=self.form_class(request.POST)
        if form.is_valid():
            new_comment=form.save(commit=False)
            new_comment.user=request.user
            new_comment.post=self.post_instance
            new_comment.save()

            messages.success(request,' your comments submitted successfully','success')
            return redirect('posts:details', self.post_instance.id,self.post_instance.slug)

        

class PostDeleteView(LoginRequiredMixin,View):
    def get(self,request ,post_id):
        post=get_object_or_404(Post,id=post_id)
        if post.user.id== request.user.id:
            post.delete()
            messages.success(request,'post deleted successfuly','success')

        else:

            messages.error(request,'you cannot delete this post','danger')
        return redirect('home:home')

class PostUpdateView(View):
    
    form_class=PostUpdateForm


    def setup(self,request,*args,**kwargs):
        self.post_instance=Post.objects.get(id=kwargs['post_id'])
        return super().setup(request,*args,**kwargs)


    def dispatch(self, request,*args,**kwarg) :
        post=self.post_instance
        if not post.user.id ==request.user.id:
            messages.error(request,'you are not allow to remove this post ','danger')
            return redirect ('home:home')

        return super().dispatch(request,*args,**kwarg)

   

    def get(self,request,*args,**kwargs):

        post=self.post_instance
        form=self.form_class(instance=post)
        return render(request,'posts/update.html',{'form':form})



    def post(self,request,*args,**kwargs):
        post=self.post_instance
        form=self.form_class(request.POST,instance=post)
        if form.is_valid():

            new_post=form.save(commit=False)
            new_post.slug=slugify(form.cleaned_data['body'][:15])
            new_post.save()
            
            messages.success(request,'you have updated post successfully', 'success')
        return redirect('posts:details', post.id,post.slug)




class PostCreateView(LoginRequiredMixin,View):
    form_class=PostUpdateForm
    def get(self,request):
        form=self.form_class()
        return render(request,'posts/create.html',{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            create_post=form.save(commit=False)
            create_post.slug=slugify(form.cleaned_data['body'][:15])
            create_post.user=request.user
            create_post.save()
            messages.success(request,'you have created new post successfully','success')
            return redirect('posts:details',create_post.id,create_post.slug)
        



class PostAddReplyView(LoginRequiredMixin,View):
    
    form_class=CommentReplyForm
    def post(self,request,*args,**kwargs):
        post=get_object_or_404(Post,id=kwargs['post_id'])
        comment=get_object_or_404(Comment,id=kwargs['comment_id'])
        form=self.form_class(request.POST)
        if form.is_valid():
            reply=form.save(commit=False)
            reply.user=request.user
            reply.post=post
            reply.reply=comment
            reply.is_reply=True
            reply.save()
            messages.success(request,'your reply submitted succesfully','success')

        return redirect ('posts:details' , post.id,post.slug)



class PostLikeView(LoginRequiredMixin,View):
    def get (self,request,post_id):
        post=get_object_or_404(Post,id=post_id)
        like=Vote.objects.filter(post=post,user=request.user).exists()
        if like:
            messages.error(request, 'you have already liked this post', 'danger')


        else:
            Vote.objects.create(post=post,user=request.user)
            messages.success(request,' you have liked this post succesfully','success')
        return redirect('posts:details',post.id,post.slug)

    
       

posts/templates/posts/create.html
{% extends 'base.html' %}


{% block content %}
    
            <form action="" method="post"  class="col-md-4" novalidate>
                {%csrf_token%}
                {{ form.as_p}}
                <input type="submit" value="Create" class="btn btn-primary ">
            </form>
    
{% endblock %}

posts/templates/posts/details.html
{% extends 'base.html' %}
{% block content %}

        <h2>{{post.body}}</h2><br><br>

            <a class="text-start" href="{% url 'account:user_profile' post.user.id %}">{{post.user.username}}</a>

            <h8>-></h8>

        <h8></h8>{{post.updated| date:"Y - M - d"}}</h8><br><br>

                {% if request.user.id == post.user.id %}
                
                    <a class="btn btn-danger"  href="{% url 'posts:delete'  post.id %}" >Delete</a>
                    <a class="btn btn-primary" href="{% url 'posts:update'  post.id%}">Update</a>

                {% endif %}
                <div class="col-md-6">
                {% if request.user.is_authenticated %}
                <a href="{% url 'posts:post_like' post.id %}" class="{% if can_like %} disabled {% endif %}btn btn-primaryrever col-md-4">Like-{{post.post_vote.count}}</a>
                        <form action=""  method = 'post'>

                            {% csrf_token %}
                            {{form.as_p}}
                            <input class= 'btn btn'type="submit" value="send">
                        </form>
                {% else %}  

                        <p>only logged in users can comment</p>

                {% endif %}

            </div>
        <hr>

              <p>  {{ comments.count }} comments</p>
            
                {% for comment in comments %}            
                    <div class="card  bg-dark text-white  col-md-6">
                        <p class="card-body">{{comment.user}}    -{{comment.created| timesince}}</p>
                        <p class="card-body ">{{comment.body}}</p><br>
                        {% if request.user.is_authenticated %}
                       
                        
                                <form action="{% url 'posts:add_reply' post.id comment.id%}" method="post">
                                        {% csrf_token %}
                                        {{reply_form.as_p}}
                                        <input type="submit" value="send">
                                </form>
                        {% endif%}



                        {% with replies=comment.reply_comment.all %}
                        {% for reply in replies  %}
                           <p class=" bg-info p-3 m-2">{{reply.user}}<br> {{reply.body}}</p>
                           <a class="btn btn-danger col-md-2" href="">Delete Reply</a>
                          
                           
                        {% endfor %} {% endwith%}
                        
                    </div>
                {% empty %}
                <H3>No comments yet</h3>
                {% endfor %}
               
            
    

{% endblock %}

posts/templates/posts/my_posts.html
{% extends 'base.html' %}


{% block content %}

<form action="" method="get">


  {{form.as_p}}

  <input type="submit" value ="Search">

  
</form>

<div class="card">
  
        {% for post in posts %}
        
                        <div class="card-body">
                     
                          <a class="btn btn-outline-dark" href="{{ post.get_absolute_url }}"> {{post.body|truncatewords:5}}</a>
                        </div>
                          
        {% endfor %}
</div>


{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}


{% block content %}
    
            <form action="" method="post"  class="col-md-4" novalidate>
                {%csrf_token%}
                {{ form.as_p}}
                <input type="submit" value="Update" class="btn btn-primary ">
            </form>
    
{% endblock %}